title: "QUARS ~ QUAlity control for Rna_Seq"
intro_text: "Easy and straightforward pre-alignment quality control for your RNAseq experiments. Let's QUARS!"
custom_logo: 'Docs/QUARS_logo.png'
custom_logo_url: 'https://github.com/TainVelasco-Luquez/QUARS'
custom_logo_title: 'QUARS_logo'
